"""MCP handler for create_test_pr (delegates to GitHubService)."""

from __future__ import annotations

import time
from pathlib import Path

from mcp.types import TextContent, Tool

from ...services import GitHubService

# =============================================================================
# Tool Definition
# =============================================================================

TOOL_DEFINITION = Tool(
    name="create_test_pr",
    description=(
        "Create a GitHub Pull Request with generated tests. "
        "Automatically creates a new branch, commits the test file, "
        "and opens a PR against the default branch."
    ),
    inputSchema={
        "type": "object",
        "properties": {
            "repo_url": {
                "type": "string",
                "description": "GitHub repository URL"
            },
            "test_code": {
                "type": "string",
                "description": "The generated test code to commit"
            },
            "target_file": {
                "type": "string",
                "description": "The source file being tested (e.g., 'src/calculator.py')"
            },
            "branch_name": {
                "type": "string",
                "description": "Branch name for PR (auto-generated if not provided)"
            },
            "pr_title": {
                "type": "string",
                "description": "PR title (auto-generated if not provided)"
            },
            "pr_description": {
                "type": "string",
                "description": "PR description (auto-generated if not provided)"
            }
        },
        "required": ["repo_url", "test_code", "target_file"]
    }
)


# =============================================================================
# Handler
# =============================================================================

async def handle(arguments: dict) -> list[TextContent]:
    """Create a PR that adds the provided generated tests to the repository."""

    repo_url = arguments.get("repo_url", "")
    test_code = arguments.get("test_code", "")
    target_file = arguments.get("target_file", "")
    branch_name = arguments.get("branch_name")
    pr_title = arguments.get("pr_title")
    pr_description = arguments.get("pr_description")

    # Validate required inputs
    if not repo_url:
        return [TextContent(type="text", text="Error: repo_url is required")]
    if not test_code:
        return [TextContent(type="text", text="Error: test_code is required")]
    if not target_file:
        return [TextContent(type="text", text="Error: target_file is required")]

    # Create the PR
    github_service = GitHubService()

    # Check for token
    if not github_service.has_token:
        return [TextContent(
            type="text",
            text="Error: GitHub token required to create PRs. Set GITHUB_TOKEN environment variable."
        )]

    # Generate defaults
    target_stem = Path(target_file).stem
    timestamp = int(time.time())

    if not branch_name:
        branch_name = f"add-tests-{target_stem}-{timestamp}"

    if not pr_title:
        pr_title = f"✅ Add tests for {target_file}"

    if not pr_description:
        pr_description = generate_pr_description(target_file, test_code)

    # Generate test file path
    test_file_path = f"tests/test_{target_stem}.py"
    commit_message = f"Add tests for {target_file}"

    # Create PR
    result = github_service.create_pull_request(
        repo_url=repo_url,
        file_path=test_file_path,
        file_content=test_code,
        branch_name=branch_name,
        commit_message=commit_message,
        pr_title=pr_title,
        pr_body=pr_description
    )

    if not result.success:
        return [TextContent(
            type="text",
            text=f"Error: {result.error.message}"
        )]

    pr_info = result.data

    # Format success response
    response = format_success_response(pr_info, test_file_path)

    return [TextContent(type="text", text=response)]


# =============================================================================
# Helper Functions
# =============================================================================

def generate_pr_description(target_file: str, test_code: str) -> str:
    """Generate a nice PR description."""
    # Count tests
    test_count = test_code.count("def test_")

    return f"""## 🧪 Automated Test Generation

This PR adds automated tests for `{target_file}`.

### Summary
- **Tests added:** {test_count}
- **Target file:** `{target_file}`

### What's included
- Unit tests for functions and methods
- Edge case coverage
- Type validation tests

### Generated by
[pytest-pipeline-mcp](https://github.com/yourusername/pytest-pipeline-mcp) 🤖

---
*Please review the generated tests and adjust as needed.*
"""


def format_success_response(pr_info, test_file_path: str) -> str:
    """Format the success response."""
    return f"""🎉 PULL REQUEST CREATED
==================================================

✅ PR successfully created!

🔗 URL: {pr_info.url}
📌 PR Number: #{pr_info.number}
🌿 Branch: {pr_info.branch}
📁 Test file: {test_file_path}

Next steps:
  1. Review the generated tests at the PR link above
  2. Run tests locally or wait for CI
  3. Use 'comment_test_results' to post test results on the PR
  4. Merge when ready!
"""
